  version: "3.3"

  services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
        - cluster.name=${CLUSTER_NAME}
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - xpack.monitoring.collection.enabled=true
        - xpack.license.self_generated.type=${LICENSE}
      mem_limit: ${MEM_LIMIT}
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      restart: always

    kibana:
      image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
      container_name: kibana
      ports:
        - 5601:5601
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - ELASTICSEARCH_USERNAME=kibana_system
        - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      depends_on:
        - elasticsearch
      restart: always

  volumes:
    elasticsearch-data:
      driver: local
